# Generated by Django 2.1.7 on 2019-03-21 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no Name yet', max_length=60)),
                ('desc', models.TextField(default='No description added')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not started', max_length=12)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no Name yet', max_length=60)),
                ('desc', models.TextField(default='No description added')),
                ('image', models.ImageField(default='static/easyLearn/mainPic.png', upload_to='media')),
                ('progress', models.TextField(default='not started')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SectionProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not started', max_length=12)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Section')),
            ],
        ),
        migrations.CreateModel(
            name='StatusActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('completion', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='StatusSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('completion', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Section')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('completion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no Name yet', max_length=60)),
                ('desc', models.TextField(default='No description added')),
                ('image', models.ImageField(default='static/easyLearn/mainPic.png', upload_to='media')),
                ('sections', models.ManyToManyField(related_name='trainings', to='easyLearn.Section')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not started', max_length=12)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Training')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='trainingprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.User'),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ManyToManyField(default=0, related_name='userTrainings', to='easyLearn.User'),
        ),
        migrations.AddField(
            model_name='statustraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Training'),
        ),
        migrations.AddField(
            model_name='sectionprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.User'),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Section'),
        ),
    ]
