# Generated by Django 2.1.7 on 2019-04-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyLearn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusactivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='statussection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='statustraining',
            name='training',
        ),
        migrations.DeleteModel(
            name='StatusActivity',
        ),
        migrations.DeleteModel(
            name='StatusSection',
        ),
        migrations.DeleteModel(
            name='StatusTraining',
        ),
    ]
