# Generated by Django 2.1.7 on 2019-04-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyLearn', '0002_auto_20190401_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(default='no Name yet', max_length=60),
        ),
        migrations.AlterField(
            model_name='activityprogress',
            name='status',
            field=models.TextField(default='not started', max_length=12),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.TextField(default='no Name yet', max_length=60),
        ),
        migrations.AlterField(
            model_name='sectionprogress',
            name='status',
            field=models.TextField(default='not started', max_length=12),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.TextField(default='no Name yet', max_length=60),
        ),
        migrations.AlterField(
            model_name='trainingprogress',
            name='status',
            field=models.TextField(default='not started', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='fname',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='lname',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=255),
        ),
    ]
