# Generated by Django 2.1.7 on 2019-04-01 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easyLearn', '0005_auto_20190401_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('completion', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='StatusSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('completion', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Section')),
            ],
        ),
        migrations.CreateModel(
            name='StatusTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('completion', models.BooleanField(default=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyLearn.Training')),
            ],
        ),
    ]
