# Generated by Django 2.1.7 on 2019-04-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyLearn', '0007_auto_20190401_2338'),
    ]

    operations = [
    ]
