# Generated by Django 2.1.7 on 2019-04-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyLearn', '0008_auto_20190412_0517'),
    ]

    operations = [
    ]
